#!/usr/bin/env python

def set_options(ctx):
  ctx.tool_options('compiler_cxx')

def configure(ctx):
  ctx.check_tool('compiler_cxx')
  ctx.check_tool('node_addon')

def build(ctx):
  t = ctx.new_task_gen('cxx', 'shlib', 'node_addon')

  # All source files to compile
  t.source = ['modulename.cc']

  # The name of the build result (the part before .node). If you change this,
  # make sure you also change the name specified in the "NODE_MODULE"
  # registration in modulename.cc
  t.target = 'modulename'
